### ISSUE TITLE
Config of your Gaming Dashboard

### ISSUE THREAD

**Issue by nichtlegacy** [JackJPowell/hass-psn#10]
Hey, would you mind sharing your yaml file of your gaming dashboard?

![image](https://github.com/user-attachments/assets/86fdfbaf-a392-4ce5-9a3b-c024a5b1ad9f)

**Comment by JackJPowell** [comment]
Sure. Do you use the same dashboard? Without that as a base, the yaml as is won't be very useful. But if you are just looking for how to extract the extra state attributes, it can give you some pointers.

**Comment by dnestico** [comment]
Please do an explanation if possible, I've made my own version but am struggling how to access the nested attributes to show the earned trophies for a currently being played game, thanks

My button-card example

```
          - type: grid
            square: false
            columns: 2
            cards:
              - type: custom:button-card
                name: |-
                  [[[
                    return states['sensor.davidnestico_status'].attributes.trophies.platinum || 'Unknown';
                  ]]] 
                entity: media_player.now_playing
                label: Platinum
                show_name: true
                show_label: true
                show_icon: true
                aspect_ratio: 1/1
                icon: mdi:trophy-variant
                tap_action:
                  action: more-info
                  haptic: medium
                styles:
                  grid:
                    - grid-template-columns: 2fr 1fr 1fr
                    - grid-template-rows: 2fr 0.1fr 1fr 1fr
                    - grid-template-areas: |
                        "i . ."
                        ". . ."
                        "n n n"
                        "l l l"
                  card:
                    - background: rgba(0, 111, 205, 0.5)
                    - border-radius: 30px
                    - box-shadow: none
                  name:
                    - color: var(--primary-text-color)
                    - font-size: 1.5rem
                    - font-weight: bold
                    - justify-self: start
                    - align-self: end
                    - margin: 0px 0px 0px 20px
                    - text-transform: capitalize
                  label:
                    - text-transform: capitalize
                    - font-size: 1rem
                    - justify-self: start
                    - align-self: start
                    - margin: 2px 0px 0px 20px
                    - color: grey
                  icon:
                    - color: '#E5E4E2'
                card_mod:
                  style: |
                    ha-card:active {
                        transform: scale(0.975);
                        transition: 0s;
                    }
              - type: custom:button-card
                name: |-
                  [[[
                    return states['sensor.davidnestico_status'].attributes.trophies.gold || 'Unknown';
                  ]]] 
                entity: media_player.now_playing
                label: Gold
                show_name: true
                show_label: true
                show_icon: true
                aspect_ratio: 1/1
                icon: mdi:trophy-variant
                tap_action:
                  action: more-info
                  haptic: medium
                styles:
                  grid:
                    - grid-template-columns: 2fr 1fr 1fr
                    - grid-template-rows: 2fr 0.1fr 1fr 1fr
                    - grid-template-areas: |
                        "i . ."
                        ". . ."
                        "n n n"
                        "l l l"
                  card:
                    - background: rgba(255, 215, 0, 0.5)
                    - border-radius: 30px
                    - box-shadow: none
                  name:
                    - color: var(--primary-text-color)
                    - font-size: 1.5rem
                    - font-weight: bold
                    - justify-self: start
                    - align-self: end
                    - margin: 0px 0px 0px 20px
                    - text-transform: capitalize
                  label:
                    - text-transform: capitalize
                    - font-size: 1rem
                    - justify-self: start
                    - align-self: start
                    - margin: 2px 0px 0px 20px
                    - color: grey
                  icon:
                    - color: rgba(255, 215, 0)
                card_mod:
                  style: |
                    ha-card:active {
                        transform: scale(0.975);
                        transition: 0s;
                    }
              - type: custom:button-card
                name: |-
                  [[[
                    return states['sensor.davidnestico_status'].attributes.trophies.silver || 'Unknown';
                  ]]] 
                entity: media_player.now_playing
                label: Silver
                show_name: true
                show_label: true
                show_icon: true
                aspect_ratio: 1/1
                icon: mdi:trophy-variant
                tap_action:
                  action: more-info
                  haptic: medium
                styles:
                  grid:
                    - grid-template-columns: 2fr 1fr 1fr
                    - grid-template-rows: 2fr 0.1fr 1fr 1fr
                    - grid-template-areas: |
                        "i . ."
                        ". . ."
                        "n n n"
                        "l l l"
                  card:
                    - background: rgba(189, 195, 199, 0.5)
                    - border-radius: 30px
                    - box-shadow: none
                  name:
                    - color: var(--primary-text-color)
                    - font-size: 1.5rem
                    - font-weight: bold
                    - justify-self: start
                    - align-self: end
                    - margin: 0px 0px 0px 20px
                    - text-transform: capitalize
                  label:
                    - text-transform: capitalize
                    - font-size: 1rem
                    - justify-self: start
                    - align-self: start
                    - margin: 2px 0px 0px 20px
                    - color: grey
                  icon:
                    - color: rgba(189, 195, 199)
                card_mod:
                  style: |
                    ha-card:active {
                        transform: scale(0.975);
                        transition: 0s;
                    }
              - type: custom:button-card
                name: |-
                  [[[
                    return states['sensor.davidnestico_status'].attributes.trophies.bronze || 'Unknown';
                  ]]] 
                entity: media_player.now_playing
                label: Bronze
                show_name: true
                show_label: true
                show_icon: true
                aspect_ratio: 1/1
                icon: mdi:trophy-variant
                tap_action:
                  action: more-info
                  haptic: medium
                styles:
                  grid:
                    - grid-template-columns: 2fr 1fr 1fr
                    - grid-template-rows: 2fr 0.1fr 1fr 1fr
                    - grid-template-areas: |
                        "i . ."
                        ". . ."
                        "n n n"
                        "l l l"
                  card:
                    - background: rgba(212, 149, 55, 0.5)
                    - border-radius: 30px
                    - box-shadow: none
                  name:
                    - color: var(--primary-text-color)
                    - font-size: 1.5rem
                    - font-weight: bold
                    - justify-self: start
                    - align-self: end
                    - margin: 0px 0px 0px 20px
                    - text-transform: capitalize
                  label:
                    - text-transform: capitalize
                    - font-size: 1rem
                    - justify-self: start
                    - align-self: start
                    - margin: 2px 0px 0px 20px
                    - color: grey
                  icon:
                    - color: rgba(212, 149, 55)
                card_mod:
                  style: |
                    ha-card:active {
                        transform: scale(0.975);
                        transition: 0s;
                    }
        columns: 2
```
