### ISSUE TITLE
Automation with Push Info playing and Game Image

### ISSUE THREAD

**Issue by monza258** [JackJPowell/hass-psn#29]
Thanks for that. 

I am new to home assistant and would like to have an automation and would like to ask if someone can help me to understand it. 

I just want an automation 
When PS is switched on, I would like to receive an info push with a picture attached to the game being played. Is this possible? 

Please 🙏

**Comment by barto95100** [comment]
Yes @monza258  but the approch is not good because when you start playstation the media_player just say : ON and in attribut no game il show just when the game realy start

for your request test this: (Work for me)

```
alias: Notification game play playstation
description: ""
triggers:
  - trigger: state
    entity_id:
      - media_player.XXXXX_ps5_console
    attribute: media_title
conditions:
  - condition: state
    entity_id: media_player.XXXXX_ps5_console
    state: playing
actions:
  - action: notify.mobile_app_xxxxxxxx
    metadata: {}
    data:
      message: "{{ states.media_player.XXXXX_ps5_console.attributes.media_title }}"
      title: PS5 - Game play
      data:
        image: >-
          {{ states.media_player.XXXXX_ps5_console.attributes.entity_picture
          }}
mode: single
```

these sens me a notification to my HA mobile companion with popup :
![IMG_149B2301F28B-1](https://github.com/user-attachments/assets/fd412314-a991-4327-b21e-d1b9a84e760f)
on hold popup
![IMG_149B2301F28B-2](https://github.com/user-attachments/assets/b7aa37be-42c2-40bf-9a4b-6360ac20fb57)
